// 기본 캐릭터 8종 (업로드한 그림을 도트로 변환한 데이터, tools/make_basic.py 로 생성)
(function (root) {
  root.BasicChars = [
 {
  "id": "penguin",
  "name": "아기 펭귄",
  "s": 2,
  "palette": {
   "a": "#f5f2ed",
   "b": "#ddd9d1",
   "c": "#bebec1",
   "d": "#dcbf9c",
   "e": "#9196a1",
   "f": "#e2a13c",
   "g": "#717888",
   "h": "#5f687a",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "..........OOOOO.........",
   "........OOhhhhhOO.......",
   "......OOhhhhhhhhhhOO....",
   "....OOhhhhhhhhhhhhhhO...",
   "...OhhhhhhhhhhhhhhhhOO..",
   "..OhhhhhhhhhhhhhhhhhhO..",
   "..OhhhhhhhhhhhhgcccghhO.",
   ".OhhhgbbbehhhhgbaaaaehO.",
   ".Ohheaaaaabhhhcaaaaaagh.",
   ".hhgaaaaaaabgeaaaaaaachO",
   "OhhcaaaaaaaaaaaaaaaaaahO",
   "OhhaaaaaaaaaaaaaaEaaaagO",
   "OhhaaaaEaaaabdbaaaaaaaeO",
   "OhgaaaaaaaabdddaaaaaaahO",
   ".hhaaaaaaaaaaaaaaaaaaeO.",
   ".OhcaaaaaaaaaaaaaaaaeO..",
   "..OOcaaaaaaaaaaaaaOO....",
   "....OOaaaaaaaabcdOO.....",
   "....OdOOddbaObbdddO.....",
   "...OddaeddbbOOabdddO....",
   "...OOdbhddbaOOabdddO....",
   "..OOOOOOddaaOOabddOO....",
   "..OOfOOOddOOOOOOddO.....",
   "..OOOOOOOOOOOOOOOO......",
   ".....OOOOOOO.OOOOO......",
   ".......OOOO...OOO......."
  ]
 },
 {
  "id": "hamster",
  "name": "아기 햄스터",
  "s": 2,
  "palette": {
   "a": "#f5f2ed",
   "b": "#ece3d8",
   "c": "#f1c9bd",
   "d": "#e6b294",
   "e": "#b9af9c",
   "f": "#dda57c",
   "g": "#d59662",
   "h": "#88805d",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "...............OOOO..",
   "..OggO........Ogggg..",
   ".OgffgO......OggdddO.",
   ".OfccfgOOOaagOggcccg.",
   ".gfccdggdaaaggggdccO.",
   ".OdcfggggaaagggggggO.",
   ".OOgggggfaaafgggggO..",
   "..OgggggdaaacggggggO.",
   ".OggggggcaaaafgggggO.",
   ".Ogggggfaaaaabfggggg.",
   ".ggggggbaaaaaabdggggO",
   "OggggfbaaaaaaaaabcdgO",
   "OgggdbEaaaaaaaaEaaaaO",
   "OgfcaabaaaabaaaaaaaaO",
   "Ocaaaaaaaabbaaaaaaaa.",
   ".OaaaaaaaaaaaaaaaaaO.",
   "..OaaaaaaaaaaaaaaOO..",
   "....OaaaaaababbbO....",
   ".....ObOObbbbbbbb....",
   "....ObbbOObcbbbbaO...",
   "...OObbabOObabbbbb...",
   "...OOhOObbcOabbbOO...",
   "...OOOOObbbbabbOO....",
   "....OOOhhhhOhhhO.....",
   ".......OeeO.OcbO.....",
   ".......OOO..OOOO....."
  ]
 },
 {
  "id": "rabbit",
  "name": "아기 토끼",
  "s": 2,
  "palette": {
   "a": "#f6f3ee",
   "b": "#f1ede8",
   "c": "#f3dad3",
   "d": "#f6cac2",
   "e": "#f7b7af",
   "f": "#f0a79d",
   "g": "#c7837b",
   "h": "#cd5b53",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "....OOO..........OOO.",
   "...ObabO........OaaO.",
   "...OaaabO.....ObaaaaO",
   "..OaaaaaO.....OaaaaaO",
   "..OaacaaaO...OaaacaaO",
   "..OabfdaaO...OaaefaaO",
   "..OabffbaO...bacffaaO",
   "...baefcaO..OaaefeaO.",
   "...OadfdaO..OabffcaO.",
   "...OabfeaO..ObcfeaO..",
   "....OacdabbbbacfbaO..",
   "....ObaaaaaaaaaaaO...",
   "...OOaaaaaaaaaaaaOO..",
   "...OaaaaaaaaaaaaaaO..",
   "..OaaaaaaaaaaaaaaaaO.",
   ".Obaaaaaaaaaaaaaaaaa.",
   ".OaaaaaaaaaaaaaaaaaaO",
   ".baaaaaaaaaaaaaaaaaaO",
   "OaaaaaaaaaaaaaabaaaaO",
   "OaaaaEbaaaaaaabEaaaaO",
   "OaaaabaaabbaaaabaaaaO",
   "OaaaaaaaabbbaaaaaaaO.",
   ".OaaaaaaaaaaaaaaaaaO.",
   ".OOaaaaaaaaaaaaaaOO..",
   "...OObbbbaabbbOOO....",
   ".....OOcfgffccO......",
   ".....OdeefffefcO.....",
   "....OacedefeebabO....",
   "....Obdedeedegfhh....",
   ".....OdceeedfhhhhO...",
   ".....deeeddeehhhO....",
   "....OccddcddcccO.....",
   "......OOcOOccOO......",
   ".......OOO.OO........"
  ]
 },
 {
  "id": "puppy",
  "name": "아기 강아지",
  "s": 2,
  "palette": {
   "a": "#f5f2ed",
   "b": "#d5d6cf",
   "c": "#ebd2bd",
   "d": "#e3bb98",
   "e": "#bcc2b6",
   "f": "#9ca992",
   "g": "#d59661",
   "h": "#546580",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   ".........OOOOOOO.........",
   "......OOgcaaaaaaOOO......",
   ".....OgggdaaaaacgggO.....",
   "....OggggdaaaaagggggO....",
   "...OgggggdaaaaaggggggO...",
   "..OggggggcaaaacgggggggO..",
   ".OgggggggcaaaacggggggggO.",
   ".OgggggggaaaaacggggggggO.",
   "OggggggggaaaaaagggggggggO",
   "OgggggggcaaaaaadggggggggO",
   "OgggggggaaaaaaacggggggggO",
   "OgggggdaEaaaaaaEcgggggggO",
   ".OggdcaaaaabaaaaaadgggggO",
   ".OOOaaaaaaaaaaaaaaaagggO.",
   "....OaaaaaaaaaaaaaaOOOO..",
   ".....OOaaaaaaaaaaaO......",
   "......OffeeabfffffO......",
   "......OOfffffffOOfOO.....",
   ".....OeOffeffefbbfOO.....",
   ".....aaeffeffefbafOO.....",
   ".....OOffffffffffOOOOO...",
   ".......OabbbbbbbbOgdaO...",
   ".......OhhhhhhhhhOgdO....",
   "........bbeO.OfebO.......",
   "........OaOO.OOOO........"
  ]
 },
 {
  "id": "cat",
  "name": "아기 고양이",
  "s": 2,
  "palette": {
   "a": "#f4f1eb",
   "b": "#edd0c2",
   "c": "#eea99b",
   "d": "#e7a86f",
   "e": "#aca5a2",
   "f": "#a4826d",
   "g": "#868280",
   "h": "#957059",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "...O...............OO..",
   "...OcO...........OddO..",
   "...ccfOO.......OOddbO..",
   "..OcccggOOOOOOOdddbbO..",
   "..Occeggggeaabddddbbb..",
   "..Ocggggggeaacdddddbb..",
   "..OgggggggeaabddddddO..",
   "..OgggggggbaabdddddddO.",
   ".OgggggggeaaaadddddddO.",
   ".Oggggggeaaaaabddddddd.",
   "OggggggeaaaaaaabddddddO",
   "OggggebaaaaaaaaabdddddO",
   "OgeeaaaEaaaaaaaaEabcddO",
   "OaaaaaaaaaaaaaaaaaaaabO",
   "OaaaaaaaaaaaaaaaaaaaaO.",
   ".OaaaaaaaaaaaaaaaaaaaO.",
   "..aaaaaaaaaaaaaaaaaaO..",
   "..OOaaaaaaaaaaaaaaOO...",
   ".OO..OOOaaaaaaaOO......",
   ".gg..ObOOaabbaaaO......",
   "OggO.OaaOaaabaaaaO.....",
   ".OaOOObOOaaaaaaaaa.....",
   ".OaaOOOOOfffhhhhbaO....",
   "...OOdOOOfhfhfhhOO.....",
   "...OOOOOOfhfhfhhO......",
   ".....OOOffhOOhfO.......",
   ".......OOOO.OOOO.......",
   ".......OOOO..OOO......."
  ]
 },
 {
  "id": "chick",
  "name": "아기 병아리",
  "s": 2,
  "palette": {
   "a": "#f1ede7",
   "b": "#d3d5d7",
   "c": "#fde08d",
   "d": "#f7dd8d",
   "e": "#f5da8a",
   "f": "#edc16d",
   "g": "#dbaa65",
   "h": "#f4a13d",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "...........OO........",
   "..........OdOO.......",
   ".........Oceee.......",
   ".......OOccccOO......",
   ".....OdccccccccO.....",
   "....OccccccccccceO...",
   "...Occccccccccccce...",
   "..OcccccccccccccccO..",
   "..dccccccccccccccce..",
   ".OcccccccccccccccccO.",
   ".OcccccccccccceEcccOO",
   ".OccceEcccddccdeccccO",
   "OccccdcccfhheccccccdO",
   "OccccccccfhfdccccccO.",
   ".OccccccccccccccceO..",
   "..OOddccccccdedOO....",
   "....OOOOOOgOOOOOO....",
   "....OOOOObbbaaaaO....",
   "...OOeaaOOObaaaaOO...",
   "...OecaaaOOOOOaaaO...",
   "...OOOaaaaOOOOOOdO...",
   ".....OaaaOOOOOOO.....",
   "......OOOOOOOOOO.....",
   "......ObOO.OObb......",
   "......ObOO..OOO......"
  ]
 },
 {
  "id": "giraffe",
  "name": "아기 기린",
  "s": 2,
  "palette": {
   "a": "#f5f1eb",
   "b": "#e9dabd",
   "c": "#fcdf8e",
   "d": "#faae94",
   "e": "#e8ba75",
   "f": "#c2a588",
   "g": "#d5935b",
   "h": "#a56a44",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   ".......OO....OO......",
   "......OhhO..Ohh......",
   ".......OO...OhO......",
   ".OOOOO.OO...OO..OccOO",
   "OccccO.OeOOOOO.OccccO",
   "OcddccOceggggcOccddcO",
   "Occddccccggeccccddcc.",
   ".OcccccccggecccccccO.",
   "..OccccccceccccccOO..",
   "...OccccccccccceeO...",
   "..OccccccccccccggO...",
   "..cccccccccccccgge...",
   ".OccccccccccccccecO..",
   ".OccccccccccccccceO..",
   ".ccccEccbbbccEccegO..",
   "Oggccaaaaaaaaaccegg..",
   "OggbaaaaaaaaaaabcgO..",
   ".gbaaaaaaaaaaaaabcO..",
   ".OaaaaaaaaaaaaaaaO...",
   "..OOaaaaaaaaaaaaO....",
   "....OOOaaaaaaOO......",
   "......OOabbaOOO......",
   ".....OOOObbOOOaO.....",
   "....OaOOOOOOObaO..OO.",
   "....OaOOOOOOhbaO.OhO.",
   "....OcOOOOOOhbhO.OhO.",
   ".....OOfffffhbOO.OO..",
   "......ffffffffOOOO...",
   "......OffOOfffO......",
   "......OOO..OOO......."
  ]
 },
 {
  "id": "tiger",
  "name": "아기 호랑이",
  "s": 2,
  "palette": {
   "a": "#f5f2ed",
   "b": "#e8dcd2",
   "c": "#f4c9a5",
   "d": "#c6c4c3",
   "e": "#f2aa72",
   "f": "#f7943d",
   "g": "#f29039",
   "h": "#84775a",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "...OO............OOO...",
   "..OgOOO.........OOggO..",
   ".OffggOOOOOOOOOOOfceg..",
   ".OeabfOOggOOggffgbacgO.",
   ".OeabefffOOOOOfffcaeg..",
   ".OecffffgOOOgffffffgO..",
   "..OgfffffgOOOgffffffO..",
   ".OgffffffOOOgfffffggO..",
   ".OgOgfffffgOffffffOOOO.",
   ".OOOfffffffgfffffffggO.",
   "OOgfffffffecefffffffgg.",
   "OgffffEffbaaacfEfffgOOO",
   "OOOfffffcaaaaacefffggO.",
   "OOgfffebaaabaaaabceefO.",
   ".Ofccbaaaaaaaaaaaaaag..",
   ".OOaaaaaaaaaaaaaaaaOO..",
   "...OOaaaaaaaaaaaaOO....",
   ".....OOdbdbabddddO..OOO",
   "......OOdddddddOOO..OgO",
   ".....OOOObddOdOOOOO.OgO",
   "....OOOOObdOOdOOOOOOOOO",
   ".....OOOOOOOddOOOOOOgO.",
   ".....OOOOOOdddOOOOgOg..",
   "......ObObddddbbdOgO...",
   "......OhhhhOOhhhhO.....",
   "......Occeh..hebbO.....",
   "......OOOOO..OOOO......"
  ]
 }
];
})(typeof window !== 'undefined' ? window : globalThis);
