// 업로드한 이미지를 도트로 변환한 캐릭터 데이터 (tools/make_mushi.py, make_gray.py, make_vintage.py 로 생성)
(function (root) {
  root.PixelChars = [
 {
  "id": "mushi",
  "name": "머시깽이",
  "s": 2,
  "palette": {
   "a": "#fefefe",
   "b": "#f6f6f6",
   "c": "#f8eddc",
   "d": "#f0e3d1",
   "e": "#e7dbc6",
   "f": "#e3d6c1",
   "g": "#c29b70",
   "h": "#907354",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   ".....O..O...",
   "....OOOOOO..",
   "...OOeOOOO..",
   "..OOeeeeeOO.",
   ".OOeeEeeeeEO",
   ".OOeeeeeeOaO",
   ".OeeeeeeeeOO",
   "OOeeeeeeeeOO",
   "OOeeeeeeeeOO",
   "OOeeeeeeeeOO",
   ".OeeeeeOeeOO",
   ".OOeeffOffOO",
   ".OfeeeOOOeOO",
   "OOeeeeefeeOO",
   "OOeeeddddeOO",
   "OOOedccccdOO",
   "OOfedccccdOO",
   ".OfeecccceOO",
   ".OOeeeccdfO.",
   ".OOOeeeeeOO.",
   "..OOOeOOfO..",
   "...OOOOOOO..",
   "....OO..O..."
  ],
  "poses": {
   "idle": [
    "......OOOOOO.............",
    "....OOOOOOOOOOOOOOOO.....",
    "...OOeeeeeefOOOaaaaOOO...",
    "..OOeeeeeeeEfOOaaaaaOOO..",
    ".OOeeeeeeeeffeOaaaaaabO..",
    "OOfeeeEeeeeeeeeOaaaaaaOO.",
    ".OOeeeeeeeeeeeeOaaaaaaOO.",
    "OOOeeeeeeeeeeeeOaaaaaaOOO",
    ".OOOfeeeeeeeeeOOaabaaaOOO",
    "...OOOfeeeeeOOOaaaaaaaOO.",
    "...OOaOOOOOOOOOOOOOOOOOO.",
    "....OOOOOOOO...OOOOOOOO..",
    ".....OOOOO..............."
   ],
   "walk": [
    ".....O..O...",
    "....OOOOOO..",
    "...OOeOOOO..",
    "..OOeeeeeOO.",
    ".OOeeEeeeeEO",
    ".OOeeeeeeOaO",
    ".OeeeeeeeeOO",
    "OOeeeeeeeeOO",
    "OOeeeeeeeeOO",
    "OOeeeeeeeeOO",
    ".OeeeeeOeeOO",
    ".OOeeffOffOO",
    ".OfeeeOOOeOO",
    "OOeeeeefeeOO",
    "OOeeeddddeOO",
    "OOOedccccdOO",
    "OOfedccccdOO",
    ".OfeecccceOO",
    ".OOeeeccdfO.",
    ".OOOeeeeeOO.",
    "..OOOeOOfO..",
    "...OOOOOOO..",
    "....OO..O..."
   ],
   "doze": [
    "...........O...........",
    "......OO..OOO..........",
    ".....OeOOOOeOO.........",
    "....OOeeOOfeeOO........",
    "....OOeeeeefeeOO.......",
    "....OffeeeeeeeeOO......",
    "...OOeeeeeeeEeefO......",
    "...OaEeeeeeefeeeOO.....",
    "...OOeeeeeeeeeeeOO.....",
    "...OOeeeeeeeeeeeOO.....",
    "...OOeeeeeeeeeeeOO.....",
    "...OOeeeeeeeeeeeOO.....",
    "....OeeeeeeeeeeeOO.OO..",
    "....OOeeeeeeeeeeOOOOOO.",
    "....OOeefeeefeeeeOOOhOO",
    "...OOOeefOOOeeeOOOOhOOO",
    "..OOeeeOeffefOOOOOOOOO.",
    ".OOeOOOOOOOOOOOOOOOO...",
    "OOgOeOOgOOOOOOeeOO.....",
    "OOgOOOOOOOOeeeeeOO.....",
    "OOgOOOOOgOOeeeeOO......",
    "OOgOOOOgOOeeeefO.......",
    ".OOgggOOOeOOOOO........",
    "..OOOOOOOOOOOO.........",
    "...OOO..OOOO...........",
    ".........OO............"
   ],
   "offline": [
    "......OO..O.............",
    ".....OOOOOOO............",
    "..OOOOOeeEeOO...........",
    ".OOOOfeeeeeefOO.........",
    ".OOefeeeeeeeeeOO........",
    "OOfeEeeeeeeeeeeOOO......",
    "OOeeeeeeeeeeeeeeOOO.....",
    "OOeeeeeeeOeffeeefOO.....",
    "OOeeeeeeefOeeedddeOO....",
    ".OOeeeeeeeeddccccdeOOO..",
    "..OOeeeeeedcccccccdeeOO.",
    "...OeeeeeedccccccccdeeO.",
    "...OOeeeeedccccccccceeOO",
    "...OfOOeeeddcccccccdeeOO",
    "....OOOOeeeedcccccdeeeOO",
    ".......OOeeeedccddeeeOOO",
    "........OOeeeeeeeeeOOOO.",
    ".........OeeeeeeeOOO....",
    "..........OOeeeOOO......",
    "...........OOOOOOO......",
    "............OOOOO......."
   ],
   "stun": [
    "........OO..O........",
    ".....OOOOOOOOO.......",
    "....OOOOeOOeOO.......",
    "...OOeeeeeeeOO.......",
    "..OOeeeeeeeeeOO......",
    "..OOeeeeEeeefOO......",
    "..OeeeefeeeefOO......",
    ".OOeeeeeeeeeeO.......",
    ".OOeeeeeeeeeOO.......",
    ".OOeeeeeeefeOO.......",
    ".OOeeeeeeOeeOO.......",
    ".OOeeeeffOfOOOO......",
    "OOeeeeeeeOeOfOOO.....",
    "OOeeeeeeddeOOfOO.....",
    "OOeeeeedccdOOOOO.....",
    "OOeeeeedccOOOeOO.....",
    "OOeeeeeedeeOeeeO.....",
    "OOeeeOeeOeeeOeeO.....",
    ".OeeeeOeOOfOOeeO.....",
    ".OOfeeeOOOObbOeO.....",
    "..OOfeeeeOObbOeO.....",
    "...OOOeeeeefOOeOO....",
    ".....OOOOOeeeOOOOO...",
    ".......OOOOOeeeOOOOO.",
    "...........OOOeeffOOO",
    "............OOOOOOOO.",
    "...............OOOO.."
   ]
  },
  "alt": {}
 },
 {
  "id": "gray",
  "name": "작은 회색고양이",
  "s": 2,
  "palette": {
   "a": "#dddddd",
   "b": "#d6d6d6",
   "c": "#d3d3d3",
   "d": "#cecece",
   "e": "#b17473",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "....O.......O....",
   "...OOO....OOOO...",
   "...OOOOOOOOcOO...",
   "...ObbbObccbdO...",
   "..OObbbbbbbbbcO..",
   ".OObbbbbbbbbbbOO.",
   ".ObbbEbbbbbbEbcO.",
   "OObbbbbbbbbbbbbOO",
   "OObbbbbbbbbbbbbOO",
   "OObbbbbbbbbbbbbOO",
   "OObbbbbbbbbbbbbOO",
   "OObbbbbbbbbbbbbOO",
   "OObbbbbbccbbbbbOO",
   ".OObbbbbcOcbbbOO.",
   "..OObbcOOOObbOO..",
   "..OOOObbOeOOOOO..",
   ".OObbbOOOOOObbOO.",
   "..OOObbbbbbbcOO..",
   "...OObbbbbbbdO...",
   "...OObbbbbbbOO...",
   "....OObddccbOO...",
   "....OOOOOOOOOO...",
   ".....OO....OO...."
  ],
  "poses": {
   "walk": [
    "....O.......O....",
    "...OOO....OOOO...",
    "...OOOOOOOOcOO...",
    "...ObbbObccbdO...",
    "..OObbbbbbbbbcO..",
    ".OObbbbbbbbbbbOO.",
    ".ObbbEbbbbbbEbcO.",
    "OObbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbOO",
    "OObbbbbbccbbbbbOO",
    ".OObbbbbcOcbbbOO.",
    "..OObbcOOOObbOO..",
    "..OOOObbOeOOOOO..",
    ".OObbbOOOOOObbOO.",
    "..OOObbbbbbbcOO..",
    "...OObbbbbbbdO...",
    "...OObbbbbbbOO...",
    "....OObddccbOO...",
    "....OOOOOOOOOO...",
    ".....OO....OO...."
   ],
   "doze": [
    ".......O..O.....",
    "......OOOOOO....",
    "....OOObOObOO...",
    "...OOObbObbOOO..",
    "..OOcbbbbbbbcOO.",
    ".OObbbbbbbbbbOO.",
    ".OcbbbbbbcbbbOOO",
    "OObbbbbbEbbbbbOO",
    "OObbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbOO",
    "OObbbbbbbbbbbcO.",
    ".OObbbbbbbbObOO.",
    "..OObbbbbdddOO..",
    "..OOOOOddOOOO...",
    "..ObbbcOccOOOO..",
    "..ObbbbbbbbOOO..",
    "..OObbbbbbOOO...",
    "..OObbbbbbOO....",
    "...OOObbdOO.....",
    ".....OOOOO......",
    "......OOO......."
   ],
   "idle": [
    ".....O......O.....",
    "....OOO....OOO....",
    "...OObOOOOOObOO...",
    "...OObbcOOObbOO...",
    "..OObccbbbbbccOO..",
    ".OObcEbbbbbbbEcOO.",
    "OObbbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbbOO",
    "OObbbbbbbbbbbbbbOO",
    ".ObbbbcbbbbbcbbOO.",
    ".OOcbbObbbbOObbOO.",
    "..OOObOOOOOObOOO..",
    "...OOOOOOOOOOOO...",
    "....OOObbbbOOO....",
    ".....OOOOOOOO.....",
    ".......OO.O......."
   ],
   "offline": [
    ".......OOOOOOO..OOOO......",
    "......OOOOOOOOOOOOOOOO....",
    "....OOObbbbbbbdOObbbOOO...",
    "...OOcbbdbbbbbbbOObbbbOO..",
    "...OcbbbbbbbbbbbbOObbccOO.",
    "..OObbbbbbbbbbbbbbObbbEbOO",
    "..ObbbbbbbbbbbbbbbOcbbbOO.",
    ".OObbbbbbbbbbbbbbbbObbbOO.",
    ".OObbbbbbbbbbbOOcbbObbbOO.",
    ".OObbbbbbbbbbbObObbObbOO..",
    ".OObbbbbbbbbbbObbbbObOO...",
    ".OObbbbbbbbbbbbbbbcOOO....",
    ".OObbbbbbbbbbbbbbbOOO.....",
    "OObbbbbbbbbbbbbbbcO.......",
    "OOOOObbbbbbbbbbbOOO.......",
    ".OOOOOObbbbbbbbOOO........",
    ".....OObOOOcOOOO..........",
    ".....OOOOOOOOOO...........",
    "......OO.................."
   ],
   "doze2": [
    "..........O.....",
    "....O....OOO....",
    "...OOOOOOObbO...",
    "...OObOOOccEbO..",
    "...OObbbbbbabOO.",
    "..OOaEbbbbbbbbOO",
    ".OObbbbbbbObcOOO",
    ".ObbbbbcdbOOOOO.",
    "OObbbbbcOOOO....",
    "OObbbbbOO.......",
    "OObbbbbOO.......",
    "OObbbbcO........",
    "OObbbbOO........",
    "OObbbbOO........",
    ".ObbbbOO.O......",
    ".OObbbcOOOO..O..",
    ".OObbbbcOOOOOOO.",
    ".OOOObbObObcbOO.",
    ".OObOOOOOOOOOO..",
    ".OObbbbbddcOO...",
    ".OObbbbbbbOOO...",
    "..OOcbbbbbOO....",
    "...OObOOOcO.....",
    "...OOOOOOOO.....",
    "....OO...O......"
   ]
  },
  "alt": {
   "hit": [
    ".......O...O.....",
    "......OOO.OOO....",
    ".....OObOOObOO...",
    "....OOcbbObbOOO..",
    "...OObbbbbcdccOO.",
    "..OObbbbbbdccdOO.",
    ".OObbbbbbEbbbbbOO",
    ".OObbbbbbbbbbbbOO",
    ".OcbbbbbbbbbbbbOO",
    ".ObbbbbbbbbbbbbOO",
    ".ObbbbbbbbbbbbbOO",
    ".OObbbbbbbbcdcbOO",
    ".OObbbbbbbdcOdbOO",
    "..OObbbbbbOOOOcO.",
    "..OOObbbbbOOOOOO.",
    ".OObcOOOOOOOOOO..",
    ".OOObbbbbbOOOOO..",
    "OOOObbbbbbbbOOO..",
    ".OOObbbbbbbbOO...",
    "..OOcOOOOOcbOO...",
    "..OOOOOOOOOOOO...",
    "...O.......OO...."
   ]
  }
 },
 {
  "id": "vintage",
  "name": "빈티지 고양이",
  "s": 2,
  "palette": {
   "a": "#fefefe",
   "b": "#f4f4f4",
   "c": "#e4e4e4",
   "d": "#c8c6c5",
   "e": "#afadac",
   "f": "#9c9b9b",
   "g": "#d96665",
   "h": "#9b7f6a",
   "i": "#857d77",
   "j": "#5d7a90",
   "O": "#262626",
   "E": "#262626",
   "W": "#ffffff"
  },
  "rows": [
   "...O.......O...",
   "..OOO.....OOO..",
   "..OOOOOOOOOOOO.",
   "..OOOOOOOOOOO..",
   "..OOaaaaceffOO.",
   ".OOaaaaaaabcOO.",
   "OOaaEaaaaaEaaOO",
   "OOaaaaaaaaaaaOO",
   "OOaaaaaaaaaaaOO",
   "OOaaaaaaaaaaaOO",
   "OOaaaaaaaaaaaOO",
   "OOaaaaaOOaaaaO.",
   ".OOaabOOaaaaOO.",
   "OOgOOOObOOOOOO.",
   "OOggggOOOgggOO.",
   "OOOgggggggggOOO",
   "OOOgggggggggOOO",
   ".OOgggggggggOO.",
   "..OOgggggggOOO.",
   "...OOOOOOOOOO..",
   "...OOOOOOOOOO..",
   "....OOO.OOOO..."
  ],
  "poses": {
   "idle": [
    "..........OOOOOO....",
    "........OOOOOOaOO...",
    ".......OOaaaaaEaO...",
    ".....OOOaaaaaaaaOO..",
    "...OOOOOOOaaaaaacOO.",
    "..OOOOggggOaaaaaaeOO",
    "..OOOggggggOaOaaaEaO",
    ".OOgggggggggOOaaaaOO",
    ".OOggggggggggObaaaOO",
    "OOOOOOOOgggggOOaaOOO",
    "OOjjjjjjOOggggOaaOOO",
    "OOjjjjjjjjOggggOOgOO",
    "OOjjjjjjjjjOgggggOO.",
    ".OjjjjjjjjjOgggOOO..",
    ".OOOjjOjjOjjOOOO....",
    "..OOOOOjjOOOOO......",
    "....OOOOOjOOO.......",
    "....OOOOOOO.........",
    ".....OOOO..........."
   ],
   "walk": [
    "......OOOOO............",
    "....OOOOOOOOO..........",
    "...OOhhhhhhhOO.........",
    "..OOhhhhhhhhhOO..OOOO..",
    "..OhhOOhhhhhOOOOObOOOO.",
    ".OOOOhhOOOOOOOOOaaOeOO.",
    ".OOOhhhhhhhhhOaaaaaaOO.",
    ".OOhhhhhhhhhOaaaaaaabOO",
    "OOhhhhhhhhhOOaaaaaEaaOO",
    "OOhhhhhhhhhOaaaaaaaaaOO",
    "OOhhhhhhhhOOOaaaaaaaaOO",
    "OOhhhhhhhhOOOOabaaaaaOO",
    "OOhhhhhhhhOggOOOabaOOO.",
    "OOhhhhhhhhOggOOaOOOOO..",
    "OOhhhhhhhhOggggOgggOO..",
    ".OOhhhhhhhOOOOOOgggOO..",
    "..OOhhhhhhOOOOggggOO...",
    "...OOOOOOOOOOOOOOOO....",
    "....OOOOOO.OOOOOOOO....",
    "............OOOOOO....."
   ],
   "doze": [
    "..........OOOOOOO.......",
    "........OOOOOOOOOO......",
    "......OOOeffeedddOO.....",
    ".....OffffffffffedOO....",
    "....OffffffffffffddOO...",
    "...OOffffffffffffffeOO..",
    "..OOfffffffffffffffeeOO.",
    "..OOOOOfOOfffffffffffOO.",
    "..OOOcOOiOfffffffffffOO.",
    "..OOccdiifOffffffffffeO.",
    ".OOccccdfedOfffffffffeOO",
    ".OOOccOccbaOffffffffffOO",
    ".OOcccOOccaOffffffffffOO",
    ".OOcccccccaOffffffffffOO",
    "..OcEcccccaOOfffffffffO.",
    "..OOcccccbOOOfffeffffOO.",
    "..OOOOccOOOgOffeeefffO..",
    ".OOggOOOOggOOfffffffOO..",
    "OOOOgggggggOOffffffOO...",
    "OOOjOOOgggOOffffffOO....",
    ".OOOOOOOOOOOOOOOOOO.....",
    "...OOOOOO...OOOO........",
    ".....OO................."
   ],
   "offline": [
    "...O.......O...",
    "..OOO.....OOO..",
    "..OOOOOOOOOOOO.",
    "..OOOOOOOOOOO..",
    "..OOaaaaceffOO.",
    ".OOaaaaaaabcOO.",
    "OOaaEaaaaaEaaOO",
    "OOaaaaaaaaaaaOO",
    "OOaaaaaaaaaaaOO",
    "OOaaaaaaaaaaaOO",
    "OOaaaaaaaaaaaOO",
    "OOaaaaaOOaaaaO.",
    ".OOaabOOaaaaOO.",
    "OOgOOOObOOOOOO.",
    "OOggggOOOgggOO.",
    "OOOgggggggggOOO",
    "OOOgggggggggOOO",
    ".OOgggggggggOO.",
    "..OOgggggggOOO.",
    "...OOOOOOOOOO..",
    "...OOOOOOOOOO..",
    "....OOO.OOOO..."
   ],
   "stun": [
    "........OO.........",
    "...OOOOOOOO........",
    "..OfOOOOffOOO......",
    "..OfaabbcdceOO.....",
    "..OeacdbaaabaOO....",
    ".OfbabbaaaaaaaOO...",
    ".OfaaaaaaaaaaaOOO..",
    ".OOaaaaaaabdaabOO..",
    ".OOcaaaaabddaabOOO.",
    "OOdcaaaaaabOOabOOO.",
    "OOObaaaaaaOOOacOOO.",
    "OOgOaaaaacOOObOgOO.",
    ".OgOOaaaabOhOOggOO.",
    ".OOOgOOOOOOOgggggO.",
    "..OOOggggggggggggOO",
    "....OOgggggggggggOO",
    ".....OgggggggggggOO",
    ".....OOggOOOOOOOOOO",
    "......OOOOOjjOOOOOO",
    "......OOOjjjOOOOOO.",
    ".......OOOOOOO.OO..",
    "........OOOO......."
   ]
  },
  "alt": {
   "hit": [
    "....OOOOOOO........",
    "..OOOOOOOOOOOOOO...",
    ".OOOOOgggOOOOOOOO..",
    ".OOOggggObaOOOfOO..",
    "OOOggggOOaaaaeffOO.",
    "OOOgggOaaaaaaadedO.",
    "OOOgggOaaaEabbaEdOO",
    "OOOggOaaaaaaaaaaaOO",
    "OOOggOaaaaaaaaaaaOO",
    "OOOggOaaaaaaaaaaaOO",
    ".OOOgOaaaaaaaaaaaOO",
    "..OOOOaaaaaaOaaaaOO",
    "....OOOaaaaaOOaabO.",
    ".....OOObaOOOOOaOO.",
    ".....OOgOOOOOOOOOO.",
    "......OOOOOOOOOOOO.",
    ".......OOO.....OO..",
    "........O.........."
   ]
  }
 }
];
})(typeof window !== 'undefined' ? window : globalThis);
